# Board Constant
SNONE  = 0
SBLACK = 1
SWHITE = 2
DRAW = 3

# Screen Constant
SQUARE_SIZE = 50
FRAME_THICKNESS = 1
RADIUS = int(SQUARE_SIZE/2 - 6)

RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Othello Constant
COLUMN_COUNT = 8
ROW_COUNT = 8
SIZE = COLUMN_COUNT * ROW_COUNT

# Tensorflow Constant
MODEL_DIRECTORY = 'model/'
MODEL_PATH = MODEL_DIRECTORY + 'train_model.ckpt'
SAVE_STEPS = 500
SAVE_MAX_TO_KEEP = 20

FACTORS = 14
HIDDEN1 = FACTORS * 4
HIDDEN2 = HIDDEN1
HIDDEN3 = HIDDEN2
HIDDEN4 = HIDDEN3
OUTPUTS = SIZE
NEURONS = OUTPUTS * 4

LEARNINGRATE = 3e-4
DISCOUNT = 0.95
EPSILONMINVALUE = 0.01